Create Italian translation
swsnr/turnon pull request #15
Opened 2024-10-28 14:26 UTC by albanobattistella

2024-10-28 15:55 UTC, swsnr requested changes

2024-10-28 15:55 UTC, swsnr commented on po/it.po
> +msgstr "Turn On"
Please translate the application name. Deepl suggests "Accendere"

2024-10-28 15:55 UTC, swsnr commented on po/it.po
> +"di gioco,utilizzando Wake On LAN (WoL)."
I'm not familiar with Italian, but shouldn't there be a space after this comma?

2024-10-29 09:53 UTC, swsnr commented
Please also update the `LINGUAS` file in this PR.

2024-10-29 10:21 UTC, albanobattistella commented on po/it.po
> +msgstr "Turn On"
> Please translate the application name. Deepl suggests "Accendere"

Hi,
not good.
Turn on is ok.
thanks.
A.

2024-10-29 10:27 UTC, albanobattistella commented on po/it.po
> +"di gioco,utilizzando Wake On LAN (WoL)."
HI,
fixed.
I cannot do a single pull request, I don't know why.

2024-10-29 11:26 UTC, swsnr commented on po/it.po
> +"di gioco,utilizzando Wake On LAN (WoL)."
Don't use the gitlab Web interface.

2024-10-29 11:30 UTC, swsnr commented on po/it.po
> +msgstr "Turn On"
Why can't you translate the application name?

2024-10-29 12:06 UTC, swsnr commented on po/it.po
> +"di gioco,utilizzando Wake On LAN (WoL)."
Or alternatively, use the Web Interface to make a commit to the patch-1 branch in your fork; that'll make it appear in this PR.

These are got basics, they shouldn't give you trouble when you intend to contribute on Github 😬

2024-10-30 18:13 UTC, closed without merging